// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGdGp8ocVF1S3FmXvJykFVR8NqeLJYKI',
    appId: '1:575683573553:web:af62065270451e09742210',
    messagingSenderId: '575683573553',
    projectId: 'amhar-fashion-store',
    authDomain: 'amhar-fashion-store.firebaseapp.com',
    storageBucket: 'amhar-fashion-store.firebasestorage.app',
    measurementId: 'G-HE6M5CE2MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2pQZDQTB_bmpD1v1UlMKmXxqti40jdQ',
    appId: '1:575683573553:android:28c36f0b6511418a742210',
    messagingSenderId: '575683573553',
    projectId: 'amhar-fashion-store',
    storageBucket: 'amhar-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlRR7VT6bGdU1RPoZSxX9NOWPCsWuYWs',
    appId: '1:575683573553:ios:077cd66af0bc847b742210',
    messagingSenderId: '575683573553',
    projectId: 'amhar-fashion-store',
    storageBucket: 'amhar-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.amharFashionStoreFlutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlRR7VT6bGdU1RPoZSxX9NOWPCsWuYWs',
    appId: '1:575683573553:ios:077cd66af0bc847b742210',
    messagingSenderId: '575683573553',
    projectId: 'amhar-fashion-store',
    storageBucket: 'amhar-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.amharFashionStoreFlutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGdGp8ocVF1S3FmXvJykFVR8NqeLJYKI',
    appId: '1:575683573553:web:20d6e790da0029de742210',
    messagingSenderId: '575683573553',
    projectId: 'amhar-fashion-store',
    authDomain: 'amhar-fashion-store.firebaseapp.com',
    storageBucket: 'amhar-fashion-store.firebasestorage.app',
    measurementId: 'G-G40ZBWQQXX',
  );
}
